### ISSUE TITLE
Control Panel Connection Error (Client network socket disconnected before secure TLS connection was established)

### ISSUE THREAD

**Issue by irieblue** [EHylands/homebridge-boschcontrolpanel_bgseries#8] opened 2022-11-30 20:13 UTC
I have a Bosch D7412GV4 (G Series) panel , and I keep seeing this message:

[11/30/2022, 12:05:01 PM] [BoschControlPanel_BGSeries] Trying to reconnect ....
[11/30/2022, 12:05:01 PM] [BoschControlPanel_BGSeries] Control Panel Connection Error (Client network socket disconnected before secure TLS connection was established)

Any way to verify this isn't related to my "Automation Passcode"?

**Comment by EHylands** [comment] 2022-11-30 20:37
Hi,
TLS handshake and authentification takes place before any plugin operations. You would get a specific error in your log file if error was related to your automation passcode.

You are the first one reporting use with a G panel.

Was the plugin functional before last update or are you trying to install for the first time ?

First step would be to confirm that your panel firmware supports TLS 1.2 as required by typescript.

Please try running the two following commands from a shell and replace with your panel ip address.

First command will detect TLS configuration on your panel.

Second command will initiate a Bosch Mode2 communication over the secure socket and should return a few bytes.

openssl s_client -connect 192.168.10.31:7700

echo -e "\x01\x01\x01" | openssl s_client -connect 192.168.10.31:7700 -quiet | xxd

**Comment by irieblue** [comment] 2022-11-30 20:50
This is the first time I am setting this up (so I have never had this working before - I am super excited if it does!

Here is the output to those commands:

$ openssl s_client -connect 10.0.1.28:7700
CONNECTED(00000003)
read:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 287 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1669841020
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

$ echo -e "\x01\x01\x01" | openssl s_client -connect 10.0.1.28:7700 -quiet | xxd
read:errno=0

**Comment by irieblue** [comment] 2022-11-30 20:52
FWIW,  I am able to access  the panel via the official Bosch RSC iOS App

**Comment by irieblue** [comment] 2022-11-30 21:11
@EHylands What Bosch panel are you developing and testing on? My Security/Bosch installer company suggested this may only work on a Bosch B series panel (along with Bosch cloud monitoring  :-(

**Comment by irieblue** [comment] 2022-11-30 21:17
<img width="1429" alt="Bsch" src="https://user-images.githubusercontent.com/24499507/204909829-9068790e-1332-4ba7-914a-ed50c7b898f1.png">
![IMG_6612D](https://user-images.githubusercontent.com/24499507/204909844-cda7e8a7-9e1c-466e-a01f-61aae2221a38.jpeg)

**Comment by EHylands** [comment] 2022-11-30 23:10
> openssl s_client -connect 10.0.1.28:7700

It looks like you panel is listenning on port 7700, but automation encryption is not enabled.

Are you using RPS to configure your B426 module ?
Is the following option set to enabled: Web and Automation Security

**Comment by irieblue** [comment] 2022-11-30 23:11
I just found out that my  GV4 panel is running  version 1, and upgrading to version 2 might cause issues for my hard wired control panels. I’ll continue to investigate on my end as I’d really like to get the home ridge functionality working on my network .

**Comment by irieblue** [comment] 2022-11-30 23:13
Also I was told by my installer (system was installed in 2014) that the RPS software only works on B series panels. Do you k ow if that is a correct assessment ?

**Comment by EHylands** [comment] 2022-11-30 23:38
> Also I was told by my installer (system was installed in 2014) that the RPS software only works on B series panels. Do you k ow if that is a correct assessment ?

https://resources-boschsecurity-cdn.azureedge.net/public/documents/Remote_Programming_S_Data_sheet_enUS_78882203019.pdf

As per Bosch documentation, RPS support D7412GV4 panels
Programming can also be done through keyboards

That being said, I am nowhere near Bosch certified installer ...

**Comment by irieblue** [comment] 2022-12-01 00:17
Thanks! That is a great resource, I'll work with my installer on this and report back. For now I will deactivate my home bridge support. Thanks for your feedback.

**Comment by EHylands** [comment] 2022-12-01 00:24
> Thanks! That is a great resource, I'll work with my installer on this and report back. For now I will deactivate my home bridge /bosch plugin. Thanks for your feedback.

I hope you find a safe way to upgrade your firmware and get Mode2 support !

For the moment, will close this issue. Please report back if you upgrade your panel.

For future reference, the following panels are supported:
- D7212G, D7412G, D9412G GV4 with firmware version 2.0 and higher
- G Series panels (B9512G and B8512G)
- RD4000
- Amax Series Panel
-  Solutions Series Panel (confirmed)
- B Series Panel (confirmed)

**Comment by EHylands** [comment] 2022-12-01 03:18
@irieblue What are the expected problems upgrading to GV4 firmware 2.03 ?

With that update, older SDI keyboards get legacy mode support and limited functionality, but you can also upgrade to newest nice looking SDI2 keyboard !

Your points are connected to b208 module which supports SDI2.

Are you using any particular fire detection circuits ?

Between firmwares updates on my B panel, they were small changes mostly related to points profiles description and I had to remove few EOL resistor installed at the panel by the initial seller. 

Previous firmware update on my side were mostly uneventful!

https://resources-boschsecurity-cdn.azureedge.net/public/documents/GV4_v2.03_firmware_u_Data_sheet_enUS_11017285131.pdf

![image](https://user-images.githubusercontent.com/90003064/204955609-35a7c472-7bc4-4cd6-b4c4-2ff9322a52b7.jpeg)

**Comment by irieblue** [comment] 2022-12-01 04:21
![IMG_6848](https://user-images.githubusercontent.com/24499507/204965048-b2af4379-9ec3-4772-801f-22861671b858.jpg)
![IMG_6843](https://user-images.githubusercontent.com/24499507/204965065-cd7e1b4b-c3c9-4825-86ca-4dc6613531eb.jpeg)

**Comment by irieblue** [comment] 2022-12-01 04:24
These are my keypads. Installer said they are not compatible with latest software? I'll look into the legacy support option. My smart home installation went to great length to hide "Wall Warts" so we powder coated the keypads to match the paint color.

**Comment by irieblue** [comment] 2022-12-01 04:32
![BoschPanel](https://user-images.githubusercontent.com/24499507/204966352-a565042a-fa8b-48c6-abc1-75848474c432.jpeg)

**Comment by irieblue** [comment] 2022-12-01 04:33
Yes, the system is tied into a [Fire] Sprinkler system.

**Comment by EHylands** [comment] 2022-12-01 04:48
> These are my keypads. Installer said they are not compatible with latest software? I'll look into the legacy support option. My smart home installation went to great length to hide "Wall Warts" so we powder coated the keypads to match the paint color.

Documentation says legacy keypads are supported with a limited command set. I did'nt found more information on the actual meaning of that info. Does that means the panel cannot be solely programmed with keypad anymore and RPS needs to be used for advanced config ? Config options are fairly limited directly using newer keypad (B942)

Found spec to upgrade firmware from 1.** to 2.

https://resources-boschsecurity-cdn.azureedge.net/public/documents/GV4_Release_Notes,_v_Release_Note_enUS_10789004683.pdf

**Comment by irieblue** [comment] 2022-12-01 05:13
Great find! Since I use a wide area DNS service , anytime I needed a programming change my installer was able to log in remotely and make the change. If I lose programming support from the keypad, it's not something i'll miss!  The keypad usage has really  been to arm and disarm , so I really don't need another "Smart Keyboard" as I think the Homekit support will be a game changer if I can get it working.

**Closed** 2023-02-15 02:48 UTC
